# Generated by Django 3.1.5 on 2021-01-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='targetNum',
            field=models.IntegerField(default=40),
        ),
    ]
