# Generated by Django 3.1.5 on 2021-01-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='phoneNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
