# Generated by Django 3.1.5 on 2021-01-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_app', '0002_applicant_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='expID',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
    ]
