# Generated by Django 3.1.5 on 2021-01-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_app', '0003_auto_20210120_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phoneNum',
            field=models.IntegerField(null=True),
        ),
    ]
