# Generated by Django 3.1.5 on 2021-01-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_app', '0004_auto_20210125_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
